# data
data: data/neo4j

# path: save the recorded output
path: "./record"

iterations: 2

# mln
mln_threshold_of_rule: 0.1
mln_threshold_of_triplet: 0.7
mln_threshold_of_rule: 0.1,
mln_iters: 100,
mln_lr: 0.0001,
mln_threads: 8
weight: 0.5

# cuda
cuda: true

# kge
model_name: TransE
hidden_dim: null
gamma: 12.0
double_entity_embedding: true
double_relation_embedding: true
# kge_model: TransE
# kge_neg: 256
# kge_dim: 100
# kge_gamma: 24
# kge_alpha: 1
# kge_lr: 0.001
# kge_iters: 10000
# kge_tbatch: 16
# kge_reg: 0.0
# kge_topk: 100

# kge_batch: 256
# keg_neg: 256
# kge_dim: 1000
# kge_gamma: 24.0
# kge_alpha: 1.0
# kge_lr: 0.0001
# kge_iters: 50000
# kge_tbatch: 16

negative_adversarial_sampling: true
adversarial_temperature: 1.0
batch_size: 16
regularization: 0.0
lr: 0.001
uni_weight: true

max_steps: 2000
log_step: 100